'use client';
import { StoryContinuity } from '@/components/story-continuity';
import { ShotVideoControls } from '@/components/shot-video-controls';
import { DurationSettings } from '@/components/duration-settings';
import { ShotImagePanel } from '@/components/shot-image-panel';
import { AgentTeam } from '@/components/agent-team';
import { AssetLibrary } from '@/components/asset-library';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Clapperboard, Film, Sparkles, Plus, Settings, Layers, ScanLine, ListVideo, FileText, Check, ChevronRight, Download, RefreshCw, Circle, AlertTriangle } from 'lucide-react';
import Image from 'next/image';
import { RawClip } from '@/components/raw-clip';
import { ApiSettings } from '@/components/api-settings';
import { ScreenplayEditor } from '@/components/screenplay-editor';
import type { Screenplay } from '@/lib/studio/screenplay';
import { ClarificationPanel } from '@/components/clarification-panel';
import { SkillCatalog } from '@/components/skill-catalog';
import { studioRequest as api } from '@/lib/studio/client';
import { Button } from '@/components/ui/button';
import { ShotEditor, movementLabels, sizeLabels } from '@/components/shot-editor';
import { StudioPreview } from '@/components/studio-preview';
import { checkContinuity } from '@/lib/studio/domain';
import { nodes } from '@/lib/studio/graph';
import type { Project, Shot, Bible, Capabilities, NodeId } from '@/lib/studio/types';

function shotImageLabel(project:Project,shot:Shot){
 if(shot.referenceMode==='demo')return '演示构图卡';
 const job=[...project.jobs].reverse().find(j=>j.shotId===shot.id&&j.kind==='image'&&j.revision===project.revision);
 if(job?.status==='queued')return '分镜画面排队中';
 if(job?.status==='running')return '分镜画面生成中';
 if(job?.status==='failed')return '分镜画面生成失败，请到生成队列查看';
 if(job?.status==='cancelled')return '分镜画面生成已停止';
 return '分镜画面未生成';
}

type View='create'|'story'|'assets'|'board'|'checks'|'prompts'|'queue'|'assembly'|'settings';
const stageViews:Record<NodeId,View>={clarify:'story',script:'story',assets:'assets',storyboard:'board',continuity:'checks',prompts:'prompts',generation:'queue',qa:'queue',assembly:'assembly',complete:'assembly'};
type Summary=Pick<Project,'id'|'title'|'updatedAt'|'mode'|'phase'>;
const bibleLabels:Record<keyof Bible,string>={character:'人物身份',appearance:'固定外观与服装',location:'场景与时空',lighting:'光线与主光方向',palette:'色彩与白平衡',props:'道具与位置',style:'画面风格',negative:'避免出现'};
const jobLabels={queued:'等待',running:'生成中',succeeded:'已完成',failed:'失败',cancelled:'已失效 / 取消'};
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function route(p:Project):View{const n=p.production?.node;if(n==='assets')return 'assets';if(n==='clarify'||n==='script')return 'story';if(n==='prompts')return 'prompts';if(n==='generation'||n==='qa')return 'queue';if(n==='assembly'||n==='complete')return 'assembly';return 'board';}
function Working(){
 const [seconds,setSeconds]=useState(0);
 useEffect(()=>{const start=Date.now();const timer=setInterval(()=>setSeconds(Math.floor((Date.now()-start)/1000)),1000);return()=>clearInterval(timer);},[]);
 return <output className="working"><RefreshCw size={15} className="spin"/>正在处理 · 已等待 {seconds} 秒。模型生成可能需要数分钟；美术格式修复最多额外一轮，请保持页面打开。</output>;
}

export default function Home(){
 const [viewedStage,setViewedStage]=useState<NodeId|null>(null);
 const [view,setView]=useState<View>('create'),[idea,setIdea]=useState(''),[duration,setDuration]=useState<number|'auto'>('auto'),[ratio,setRatio]=useState<Project['ratio']>('16:9'),[mode,setMode]=useState<Project['mode']>('demo');
 const [project,setProject]=useState<Project|null>(null),[projects,setProjects]=useState<Summary[]>([]),[caps,setCaps]=useState<Capabilities|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [answers,setAnswers]=useState<Record<string,string>>({}),[script,setScript]=useState<Screenplay>({title:'',logline:'',synopsis:''}),[bible,setBible]=useState<Bible|null>(null),[seed,setSeed]=useState(42),[selected,setSelected]=useState(0),[draft,setDraft]=useState<Shot|null>(null),[reviewNotes,setReviewNotes]=useState<Record<string,string>>({});
 const active=useRef<Project|null>(null);
 const pending=project?.jobs.some(j=>j.status==='queued'||j.status==='running')??false;
 const issues=project?.plan?checkContinuity(project.plan,project.duration):[];
 const editable=(s:Shot)=>JSON.stringify(s,(key,value)=>['referenceUrl','videoUrl','referenceMode','videoMode'].includes(key)?undefined:value);
 const dirty=!!(draft&&project?.plan&&editable(draft)!==editable(project.plan.shots[selected]));
 function sync(p:Project,navigate=false,index=0){if(navigate)setViewedStage(null);setProject(p);active.current=p;localStorage.setItem('frame-active-project',p.id);setSelected(index);setAnswers(p.brief&&!p.brief.ready?{...p.answers,...Object.fromEntries(p.questions.map(q=>[q.id,'']))}:p.answers);if(p.production?.script)setScript(p.production.script);setBible(p.plan?.bible??p.production?.assets?.bible??null);setSeed(p.production?.assets?.seed??42);setDraft(p.plan?.shots[index]?structuredClone(p.plan.shots[index]):null);if(navigate)setView(route(p));}
 function selectShot(index:number){setSelected(index);setDraft(project?.plan?.shots[index]?structuredClone(project.plan.shots[index]):null);}
 async function refresh(){setProjects(await api<Summary[]>('list'));}
 useEffect(()=>{void Promise.all([api<Capabilities>('status'),api<Summary[]>('list')]).then(async([c,list])=>{setCaps(c);setProjects(list);const id=localStorage.getItem('frame-active-project');if(id&&list.some(p=>p.id===id)){const p=await api<Project>('get',{id});sync(p,true);}}).catch(e=>setError(e.message));},[]);
 const currentId=project?.id;
 useEffect(()=>{if(!pending||!currentId)return;let stopped=false;let timer:ReturnType<typeof setTimeout>;const id=currentId;const poll=async()=>{try{const p=await api<Project>('poll',{id});if(!stopped&&active.current?.id===id&&p.revision>=active.current.revision){setProject(p);active.current=p;}}catch(e){if(!stopped)setError((e as Error).message);}finally{if(!stopped)timer=setTimeout(poll,1400);}};timer=setTimeout(poll,700);return()=>{stopped=true;clearTimeout(timer);};},[currentId,pending]);
 async function act(action:string,data:Record<string,unknown>={},navigate=false){setBusy(true);setError('');setNotice('');try{const p=await api<Project>(action,{id:project?.id,revision:project?.revision,...data});sync(p,navigate,action==='story_next'?0:selected);await refresh();return p;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function open(id:string){if(dirty){setError('请先保存当前镜头修改。');return;}setBusy(true);setError('');try{const p=await api<Project>('get',{id});setSelected(0);sync(p,true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function navigate(v:View){if(dirty){setError('请先保存当前镜头修改，再切换页面。');return;}setView(v);setViewedStage(null);setError('');}
 function openStage(node:NodeId){if(dirty){setError('请先保存当前镜头修改，再回看其他步骤。');return;}navigate(stageViews[node]);setViewedStage(node);}
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'read_production_state',description:'Read the current film project, graph stage, shot count, and continuity warnings.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');const p=active.current;return p?{id:p.id,title:p.title,node:p.production?.node,mode:p.mode,shots:p.plan?.shots.length??0,issues:p.plan?checkContinuity(p.plan):[]}:{project:null};}}, {signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const g=project?.production;
 const navItems:{v:View;icon:typeof Film;label:string;enabled:boolean}[]=[{v:'story',icon:FileText,label:'创意与剧本',enabled:!!project},{v:'assets',icon:Layers,label:'角色与场景',enabled:!!g?.assets},{v:'board',icon:Film,label:'分镜与运镜',enabled:!!project?.plan},{v:'checks',icon:ScanLine,label:'连续性检查',enabled:!!project?.plan},{v:'prompts',icon:Sparkles,label:'提示词',enabled:!!g?.prompts},{v:'queue',icon:ListVideo,label:'生成与审片',enabled:!!project?.plan},{v:'assembly',icon:Clapperboard,label:'剪辑预演',enabled:!!project?.plan}];
 return <div className="studio">
 <aside className="rail"><div className="brand"><Clapperboard/> FRAME <span>AI 导演工作台</span></div><Button className="new-project" variant="outline" disabled={busy} onClick={()=>{if(dirty){setError('请先保存当前镜头修改。');return;}setProject(null);setView('create');setSelected(0);setIdea('');localStorage.removeItem('frame-active-project');}}><Plus/>新建作品</Button><div className="rail-label">制作工作台</div><nav>{navItems.map(({v,icon:Icon,label,enabled})=><button key={v} className={'nav '+(view===v?'active':'')} disabled={!enabled||busy} onClick={()=>navigate(v)}><Icon size={17}/>{label}</button>)}</nav><div className="rail-label recent-label">最近作品</div><div className="recent">{projects.slice(0,5).map(p=><button key={p.id} title={p.title} disabled={busy} onClick={()=>void open(p.id)}><span className="project-dot"/>{p.title}</button>)}</div><div className="rail-note"><button className={'nav '+(view==='settings'?'active':'')} onClick={()=>navigate('settings')}><Settings size={17}/>服务与接入</button><span className="status-dot"/> 保存在本机 · {project?.mode==='live'?'真实 API':'演示模式'}</div></aside>
 <main className="workspace"><header><span>工作空间 <span className="slash">/</span> {project?.title||'新作品'}</span><div className="header-actions">{project&&<Button variant="ghost" onClick={()=>download(project,'frame-project-'+project.id+'.json')}><Download/>项目 JSON</Button>}<span className="pill">{project?.mode==='live'?'LIVE · 真实 API':'DEMO · 本地演示'}</span></div></header>
 {error&&<div role="alert" className="banner error"><AlertTriangle size={18}/>{error}<button aria-label="关闭错误" onClick={()=>setError('')}>×</button></div>}{notice&&<output className="banner">{notice}</output>}{busy&&<Working/>}
 {project&&g&&view!=='settings'&&<><nav className="graph-strip" aria-label="制作步骤，可点击回看">{nodes.map((n,i)=>{const current=nodes.findIndex(v=>v.id===g.node),available=i<=current;return <button type="button" key={n.id} disabled={busy||!available} onClick={()=>openStage(n.id)} aria-current={g.node===n.id?'step':undefined} title={available?'查看'+n.label:'尚未到达此步骤'} className={(g.node===n.id?'current':i<current?'done':'')+((viewedStage===n.id||(!viewedStage&&g.node===n.id&&view===stageViews[n.id]))?' viewing':'')}><i>{i<current?<Check size={12}/>:String(i+1).padStart(2,'0')}</i>{n.label}</button>;})}</nav><div className="stage-navigation"><span>制作进度：{nodes.find(n=>n.id===g.node)?.label} · 已完成步骤可点击回看</span>{view!==stageViews[g.node]&&<><span>正在回看：{nodes.find(n=>n.id===viewedStage)?.label||navItems.find(n=>n.v===view)?.label}</span><Button variant="outline" disabled={busy} onClick={()=>openStage(g.node)}>返回当前步骤</Button></>}<small>回看不会回退制作进度；保存修改或重新生成才会更新下游内容。</small></div></>}
 {view==='create'&&<><section className="intro"><div className="eyebrow">FROM AN IDEA TO A SEQUENCE</div><h1>让脑海中的画面，<br/><em>有序发生。</em></h1><p>说出你的故事。一起确定创意，再把它变成每一个镜头。</p></section><section className="composer panel"><div className="section-head"><h2><Sparkles size={19}/> 你的第一幕是什么？</h2><span>01 / 创意</span></div><textarea aria-label="描述你的创意" maxLength={4000} placeholder="例如：一个女孩在雨后的旧车站，发现一封寄给未来的信。电影感，有一个温暖的结尾。" value={idea} onChange={e=>setIdea(e.target.value)}/><div className="creation-options"><label>目标时长<select value={duration} onChange={e=>setDuration(e.target.value==='auto'?'auto':Number(e.target.value))}><option value="auto">自动估算（可不指定）</option>{[12,24,30,60,90,120].map(n=><option key={n} value={n}>{n} 秒</option>)}</select></label><label>画幅<select value={ratio} onChange={e=>setRatio(e.target.value as Project['ratio'])}><option>16:9</option><option>9:16</option><option>1:1</option></select></label><label>生成方式<select value={mode} onChange={e=>setMode(e.target.value as Project['mode'])}><option value="demo">演示模式 · 不消耗 API</option><option value="live" disabled={!caps?.llm}>真实 API {caps?.llm?'':'· 尚未配置'}</option></select></label></div><div className="composer-footer"><span>先澄清意图，再确认剧本与镜头</span><Button disabled={!idea.trim()||busy} onClick={()=>void act('create',{idea,duration,ratio,mode},true)}>开始导演对话 <ArrowUpRight/></Button></div></section><div className="examples"><span>试一个创意</span>{['雨后的旧车站，一封寄给未来的信','凌晨的面包店，第一位客人是失眠的宇航员','一只纸船穿过城市，最终回到孩子手里'].map(v=><button key={v} onClick={()=>setIdea(v)}>{v}<ArrowUpRight size={14}/></button>)}</div><div className="workflow">编剧 <span>→</span> 美术 <span>→</span> 导演 <span>→</span> 场记 <span>→</span> 执行制片 <span>→</span> 审片与剪辑</div><p className="help">演示使用规则与模板模拟角色节点；真实模式可调用语言模型。不会把演示预演标为真实生成影片。</p></>}
 {project&&<StoryContinuity key={project.id+':'+project.revision} project={project} busy={busy||dirty||pending} act={act}/>}
 {view==='story'&&project&&<><div className="page-title"><div><div className="eyebrow">WRITER / 编剧</div><h1>{g?.node==='clarify'?'先把故事说清楚。':'让故事落到纸上。'}</h1></div><span className="pill">人工确认点 01</span></div><div className="two-col"><section className="panel"><h2>原始创意</h2><DurationSettings key={project.id+':'+project.revision} project={project} busy={busy} act={act}/><p className="idea-quote">{project.idea}</p><div className="meta-row"><span>{project.duration} 秒</span><span>{project.ratio}</span><span>{project.mode==='demo'?'演示模板':'语言模型'}</span></div><ClarificationPanel project={project} answers={answers} onAnswers={setAnswers} busy={busy} onAction={act}/></section><section className="panel">{g?.script?<><div className="section-head"><h2>剧本草案</h2><span>{g.scriptApproved?'已确认':'可编辑'}</span></div><label>片名<input value={script.title} disabled={g.scriptApproved} onChange={e=>setScript({...script,title:e.target.value})}/></label><label>一句话故事<textarea value={script.logline} disabled={g.scriptApproved} onChange={e=>setScript({...script,logline:e.target.value})}/></label><label>故事梗概<textarea className="script-text" value={script.synopsis} disabled={g.scriptApproved} onChange={e=>setScript({...script,synopsis:e.target.value})}/></label><ScreenplayEditor script={script} onChange={setScript} disabled={g.scriptApproved||busy} total={project.duration}/><Button variant="outline" disabled={busy||pending} onClick={()=>void act('rewrite_script',{answers:project.answers},true)}>{script.schemaVersion===2?'重新编剧（下游需重做）':'重写为结构化剧本'}</Button>{!g.scriptApproved&&<Button disabled={busy||script.schemaVersion!==2} onClick={()=>void act('approve_script',{script},true)}><Check/>确认剧本，提取资产</Button>}{g.scriptApproved&&<Button variant="outline" onClick={()=>navigate('assets')}>查看资产设定 <ChevronRight/></Button>}</>:<div className="empty-state"><FileText size={36}/><h2>剧本从你的回答开始</h2><p>明确主角、场景与结尾后，编剧会给出可编辑的故事草案。</p></div>}</section></div></>}
 {view==='assets'&&bible&&project&&<><AssetLibrary project={project} busy={busy} act={act}/><div className="page-title"><div><div className="eyebrow">ART DIRECTOR / 美术</div><h1>让每一镜，认得同一个世界。</h1></div><span className="pill">{g?.assets?.locked?'资产已锁定':'待确认'}</span></div><section className="panel"><div className="section-head"><h2>角色与场景设定集</h2><span>生成时传递给每个镜头</span></div><div className="form-grid assets-grid">{Object.entries(bibleLabels).map(([k,l])=><label key={k}>{l}<textarea value={bible[k as keyof Bible]} onChange={e=>setBible({...bible,[k]:e.target.value})}/></label>)}</div><Button variant="outline" disabled={busy} onClick={()=>void act('asset_save_bible',{bible})}>保存设定并建立新一批资产候选</Button><label className="seed">固定 Seed<input type="number" disabled={g?.node!=='assets'} min={0} max={2147483647} value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label><p className="help">Seed 仅在供应商支持时生效；不能单独保证角色一致性。参考图会按镜头顺序继承。</p><Button disabled={busy} onClick={()=>void act(g?.node==='assets'?'approve_assets':'bible',g?.node==='assets'?{bible,seed}:{bible},true)}>{g?.node==='assets'?'锁定资产，生成分镜':'保存设定 · 使下游素材失效'} <ArrowUpRight/></Button></section></>}
 {view==='board'&&project?.plan&&<><div className="page-title"><div><div className="eyebrow">DIRECTOR / 导演</div><h1>把故事，拆成镜头。</h1><p>{project.plan.shots.length} 个镜头 · {project.plan.shots.reduce((n,s)=>n+s.duration,0)} 秒 · {project.ratio}</p></div><Button disabled={dirty||busy} variant="outline" onClick={()=>navigate('checks')}><ScanLine/>检查衔接</Button></div><section className="panel"><p>已确认的美术设定图用于保持人物、场景和道具一致；下方展示的是每个镜头单独生成的画面。</p><p className="help">{project.plan.shots.filter(s=>s.referenceUrl).length} / {project.plan.shots.length} 个镜头已有画面。先完成连续性检查和提示词确认，再进入生成队列点击“生成分镜画面”。未提交任务时不会自动生图。</p></section><div className="board-layout"><div><div className="shot-grid">{project.plan.shots.map((s,i)=><button key={s.id} className={'shot-card '+(selected===i?'selected':'')} disabled={busy} onClick={()=>{if(dirty){setError('请先保存当前镜头。');return;}selectShot(i);}}><div className="shot-frame" style={{aspectRatio:project.ratio.replace(':','/')}}>{s.referenceUrl?<Image src={s.referenceUrl} alt={s.title} width={640} height={360} unoptimized/>:<><span className="frame-number">{String(i+1).padStart(2,'0')}</span><span className="frame-caption">{shotImageLabel(project,s)}</span></>}<span className="frame-time">{s.duration}s</span></div><div className="shot-info"><span className="shot-index">SHOT {String(i+1).padStart(2,'0')}</span><h3>{s.title}</h3><p>{s.description}</p><div className="shot-tags"><span>{sizeLabels[s.size]}</span><span>{s.camera.lens}mm</span><span>{movementLabels[s.camera.movement]}</span></div></div></button>)}</div><div className="timeline" aria-label="分镜时间轴">{project.plan.shots.map((s,i)=><button key={s.id} style={{flex:s.duration}} className={selected===i?'selected':''} disabled={dirty} onClick={()=>selectShot(i)}><span>{String(i+1).padStart(2,'0')}</span><small>{s.duration}s</small></button>)}</div><p className="help">运镜是可编辑的创作指令。供应商是否精确执行路径，仍需检查生成素材。</p></div><section className="panel inspector">{draft&&<ShotImagePanel project={project} shot={draft} busy={busy} dirty={dirty} act={act}/>} {draft&&<ShotVideoControls key={project.id+draft.id+project.updatedAt} project={project} shot={project.plan.shots[selected]} busy={busy||dirty} act={act}/>} {draft&&<ShotEditor shot={draft} onChange={setDraft} onMotionPlan={notes=>void act('motion_plan',{shotId:draft.id,notes})} onSave={()=>void act('shot',{shot:draft})} busy={busy} dirty={dirty}/>}</section></div></>}
 {view==='checks'&&project?.plan&&<><AgentTeam project={project} busy={busy} act={act}/><div className="page-title"><div><div className="eyebrow">CONTINUITY / 场记</div><h1>切换镜头，保持故事。</h1></div><span className="pill">{issues.length} 项待复核</span></div><section className="panel" aria-label="场记自动修订入口"><h2>按场记意见修正分镜</h2><p>已有当前版本的专业场记报告后，可在这里直接修订，不必滚动到问题列表底部。</p><Button disabled={busy||project.mode==='demo'||g?.autoRun?.status==='running'||g?.continuityReview?.revision!==project.revision||!g?.continuityReview?.findings.length} onClick={()=>void act('continuity_fix')}>按本次意见自动修正分镜（语言模型计费，不生图）</Button>{(!g?.continuityReview||g.continuityReview.revision!==project.revision)&&<p>当前没有有效的场记报告，请先运行专业场记审查。</p>}<Button variant="outline" disabled={busy||!['storyboard','continuity'].includes(g?.node||'')} onClick={()=>void act('continuity_review')}>运行专业场记审查</Button></section><section className="panel"><div className="section-head"><h2>结构检查与文字差异复核</h2><span>动作 · 服装 · 道具 · 轴线 · 方向 · 时长</span></div>{issues.length?issues.map((i,n)=><div key={n} className={'issue '+i.level}><AlertTriangle size={18}/><div><strong>{i.shotId.toUpperCase()}</strong><p>{i.message}</p></div><Button variant="ghost" onClick={()=>{selectShot(project.plan!.shots.findIndex(s=>s.id===i.shotId));navigate('board');}}>调整</Button></div>):<div className="pass"><Check/>规则检查未发现冲突。</div>}<p className="help">文字描述不同不代表画面穿帮。请结合前后依据复核；空镜切人物、局部特写和正常动作推进都可能合理。实际画面仍需生成后审查。</p><Button variant="outline" disabled={busy||!['storyboard','continuity'].includes(g?.node||'')} onClick={()=>void act('continuity_review')}>运行专业场记审查</Button>{g?.continuityReview&&<section className="semantic-review"><h3>专业场记意见 · {project.mode==='demo'?'演示':'模型语义审查'}</h3><p>{g.continuityReview.summary}</p><Button variant="outline" disabled={busy||project.mode==='demo'||g.autoRun?.status==='running'||g.continuityReview.revision!==project.revision||!g.continuityReview.findings.length} onClick={()=>void act('continuity_fix')}>按本次意见自动修正分镜（语言模型计费，不生图）</Button><p className="help">保留已确认剧本、对白及场次时长。修订前备份，校验失败不覆盖；成功后旧素材失效，请重新运行场记审查再编译提示词。</p>{g.continuityReview.findings.map((f,i)=><div className="issue" key={i}><div><strong>{f.shotId}</strong><p>{f.message}</p><small>依据：{f.evidence}</small><p>建议：{f.suggestion}</p></div></div>)}</section>}<Button disabled={busy||g?.continuityReview?.revision!==project.revision||issues.some(i=>i.level==='error')||!['storyboard','continuity'].includes(g?.node||'')} onClick={()=>void act('compile',{},true)}>确认检查，编译提示词 <ArrowUpRight/></Button></section></>}
 {view==='prompts'&&project&&<><div className="page-title"><div><div className="eyebrow">PROMPT COMPILER / 提示词编译</div><h1>把导演意图，交给模型。</h1></div><span className="pill">人工确认点 02</span></div><section className="panel"><p>每镜携带角色设定、起止状态、摄影指令和前镜衔接信息。当前输出统一网关协议，供应商适配器负责转换为具体字段。</p>{g?.prompts?.map((p,i)=><details key={p.shotId} open={i===0}><summary>SHOT {String(i+1).padStart(2,'0')} · 结构化提示词</summary><pre>{JSON.stringify(JSON.parse(p.prompt),null,2)}</pre></details>)}<p className="help">{project.mode==='demo'?'演示模式不调用付费 API。':'真实生成会调用已配置的供应商并可能产生费用。'} 生成时会补充刚完成的上游素材链接；编辑分镜后必须重新批准。</p><Button disabled={busy||g?.node!=='prompts'} onClick={()=>void act('approve_render',{},true)}><Check/>批准当前版本，进入生成</Button></section></>}
 {view==='queue'&&project&&<><div className="page-title"><div><div className="eyebrow">EXECUTOR + REVIEWER / 执行与审片</div><h1>{g?.node==='qa'?'看看镜头是否成立。':'让镜头依次成形。'}</h1></div><span className="pill">{pending?'队列运行中':'等待操作'}</span></div><section className="panel"><div className="queue-actions"><Button disabled={busy||pending||g?.node!=='generation'} onClick={()=>void act('enqueue',{kind:'image'})}><Layers/>生成分镜画面 / 重试失败</Button><Button disabled={busy||pending||g?.node!=='generation'} onClick={()=>void act('enqueue',{kind:'video'})}><Film/>生成片段 / 重试失败</Button><Button variant="outline" disabled={busy||!pending} onClick={()=>void act('cancel')}>停止队列</Button></div><p className="help">{project.mode==='demo'?'演示生成构图卡与预演就绪状态，不会调用图像或视频模型。':'任务依次执行；单镜任务及视频任务无需等待前镜视频。'} 队列在工作台打开时推进，关闭后再次打开可继续跟踪。</p><div className="job-list">{project.plan?.shots.map((s,i)=><div key={s.id}><ShotVideoControls key={s.id+project.updatedAt} project={project} shot={s} busy={busy} act={act}/><div className="job-row"><span className="job-number">{String(i+1).padStart(2,'0')}</span><div><h3>{s.title}</h3><small>{s.duration} 秒 · {sizeLabels[s.size]}</small></div>{(['image','video'] as const).map(kind=>{const j=[...project.jobs].reverse().find(j=>j.shotId===s.id&&j.kind===kind);return <span key={kind} className={'job-state '+(j?.status||'')} title={j?.error}>{j?.status==='running'?<RefreshCw size={14} className="spin"/>:j?.status==='succeeded'?<Check size={14}/>:<Circle size={12}/>} {kind==='image'?'分镜画面':'片段'} · {j?jobLabels[j.status]:'未生成'}{j?.error&&<small>{j.error}</small>}</span>;})}</div></div>)}</div></section>
 {g?.node==='qa'&&<section className="panel qa-panel"><h2>逐镜审查 · 最多 {g.maxRetries} 次返工</h2><p className="help">演示模式只验证流程；真实模式请播放下方素材。审查意见会带入重试请求。</p>{g.qa.map(q=>{const s=project.plan!.shots.find(s=>s.id===q.shotId)!;return <div className="review-row" key={q.shotId}><h3>{s.title} <small>返工 {q.attempt}/{g.maxRetries} · {q.verdict==='passed'?'已通过':'待复核'}</small></h3><p>{q.notes}</p>{s.videoUrl&&<RawClip url={s.videoUrl} title={s.title} dialogue={s.dialogue}/>}<input aria-label={s.title+'审查意见'} placeholder="审查意见，例如：主角方向一致，动作衔接清楚" value={reviewNotes[q.shotId]||''} onChange={e=>setReviewNotes({...reviewNotes,[q.shotId]:e.target.value})}/><div className="queue-actions"><Button disabled={busy||q.verdict==='passed'} onClick={()=>void act('review',{shotId:q.shotId,verdict:'passed',notes:reviewNotes[q.shotId]||'人工确认本镜头可进入组装。'})}><Check/>通过</Button><Button variant="outline" disabled={busy||q.attempt>=g.maxRetries||!reviewNotes[q.shotId]?.trim()} onClick={()=>void act('review',{shotId:q.shotId,verdict:'rejected',notes:reviewNotes[q.shotId]})}>退回并重试</Button></div></div>;})}<Button variant="outline" onClick={()=>navigate('assembly')}>查看整片分镜预演</Button></section>}
 {['assembly','complete'].includes(g?.node||'')&&<Button className="next-action" onClick={()=>navigate('assembly')}>审片完成，进入组装 <ArrowUpRight/></Button>}
 <details className="panel event-log"><summary>状态图执行记录 · {g?.events.length??0} 条</summary>{g?.events.map((e,i)=><div key={i}><small>{new Date(e.at).toLocaleTimeString('zh-CN')} / {e.role}</small><p>{e.message}</p></div>)}</details></>}
 {view==='assembly'&&project?.plan&&<><div className="page-title"><div><div className="eyebrow">EDITOR / 剪辑</div><h1>先看节奏，再看成片。</h1></div><span className="pill">动态分镜预演</span></div><section className="panel"><StudioPreview key={project.id+'-'+project.revision} project={project} canExport={['assembly','complete'].includes(g?.node||'')&&!!g?.editPlan} onExport={()=>void act('complete')}/>{!['assembly','complete'].includes(g?.node||'')&&<p className="help">完成生成并逐镜通过审查后，即可导出预演视频。</p>}{['assembly','complete'].includes(g?.node||'')&&<section className="editorial-plan"><Button disabled={busy} onClick={()=>void act('prepare_assembly')}>生成专业剪辑与声音方案</Button>{g?.editPlan&&<><h3>{g.editPlan.summary}</h3>{g.editPlan.notes.map(n=><div className="known-fact" key={n.shotId}><strong>{n.shotId}</strong><p>剪辑：{n.edit}</p><p>声音：{n.audio}</p></div>)}{g.editPlan.limitations.map((n,i)=><p className="help" key={i}>{n}</p>)}</>}</section>}<div className="queue-actions"><Button variant="outline" onClick={()=>download({editorialPlan:g?.editPlan??null,title:project.title,ratio:project.ratio,clips:project.plan!.shots.map(s=>({id:s.id,duration:s.duration,url:s.videoUrl??null,dialogue:s.dialogue,sound:s.sound,transition:s.transition})),audio:{status:'not_generated',note:'TTS/SFX/BGM 需接入音频服务'},assembly:{status:'not_assembled',note:'真实片段拼接需使用后期脚本'}},'frame-timeline.json')}><Download/>导出后期时间轴</Button><Button variant="outline" onClick={()=>navigate('queue')}>返回生成与审片</Button></div></section></>}
 {view==='settings'&&<><div className="page-title"><div><div className="eyebrow">PROVIDERS / 服务</div><h1>创作流程，与模型解耦。</h1></div></div><ApiSettings onSaved={setCaps}/>{project&&<AgentTeam project={project} busy={busy} act={act}/>}<SkillCatalog/><section className="panel"><h2>本地服务状态</h2><div className="provider-list">{[{name:'语言模型',ready:caps?.llm,model:caps?.llmModel,desc:'OpenAI 兼容 Chat Completions 协议；编剧、美术、导演分角色调用。'},{name:'图像生成 / 图生图',ready:caps?.image,model:caps?.imageModel,desc:'统一媒体网关；传递角色设定、Seed 和参考图。'},{name:'视频生成',ready:caps?.video,model:caps?.videoModel,desc:'异步任务协议；提交、查询和衔接素材交接。'}].map(v=><div key={v.name} className="provider-row"><div><h3>{v.name}</h3><p>{v.desc}</p><small>{v.model}</small></div><span className={v.ready?'pill':'muted-pill'}>{v.ready?'已配置，尚需实测':'未配置 · 使用演示'}</span></div>)}</div><p className="help">上方设置保存到本机服务端，优先于 .env 生效。密钥不回显，也不会写入项目导出文件。网关协议见项目 README。</p><div className="capability-note"><h3>本版边界</h3><p>已实现状态图、人工确认、规则场记、顺序队列、人工审片返工及无声 WebM 预演。配置视觉审查网关可启用自动反思与有限重试；自动 TTS/SFX/BGM 和供应商专属适配需继续接入。真实模式不会偷偷回退到演示。</p></div></section></>}
 </main></div>;
}





