'use client';
import { useEffect, useState } from 'react';
import { Save, KeyRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Capabilities } from '@/lib/studio/types';
import type { SettingsView } from '@/lib/studio/settings';
import { studioRequest } from '@/lib/studio/client';

const groups=[
 {title:'语言模型',description:'支持 OpenAI 兼容的 Chat Completions 接口。填写基础地址，不需要加 /chat/completions。',fields:[['LLM_BASE_URL','API 基础地址','https://api.deepseek.com'],['LLM_MODEL','模型 ID','填写账户可用的模型 ID'],['LLM_API_KEY','API Key','']]},
 {title:'fal.ai 素材生成',description:'人物与场景主图使用 FLUX.2 Turbo，普通修改使用 FLUX Edit，多参考图与分镜合成使用 Seedream 4.5。独立密钥，不会复用 OpenAI 或 MiniMax 密钥。',fields:[['FAL_API_KEY','fal.ai API Key','']]},
 {title:'图像服务与 OpenAI 备用',description:'选择 OpenAI 后，参考图直接调用官方接口并保存在本机。使用独立的 OpenAI API Key；当前为文生图，不传入前镜参考图。横竖图分别生成 1536×1024 / 1024×1536，分镜预览按画幅裁切。',fields:[['IMAGE_PROVIDER','图像服务',''],['OPENAI_IMAGE_MODEL','GPT 图像模型',''],['OPENAI_IMAGE_API_KEY','OpenAI API Key','']]},
 {title:'视频与备用图像网关',description:'MiniMax 官方地址自动使用 H3 原生 V2 接口（支持 /v1 地址兼容），模型填写 MiniMax-H3 或 MiniMax-H3-Max，输出 768P。其他地址继续使用自建 /jobs 网关协议。',fields:[['MEDIA_GATEWAY_URL','媒体网关地址','https://your-gateway.example'],['IMAGE_MODEL','图像模型 ID','网关中的图像模型 ID'],['VIDEO_MODEL','视频模型 ID','网关中的视频模型 ID'],['MEDIA_API_KEY','媒体 API Key','']]},
 {title:'视觉审片（可选）',description:'网关需支持 /review；未配置时使用人工审片。',fields:[['QA_GATEWAY_URL','审片网关地址','https://your-review-gateway.example'],['QA_API_KEY','审片 API Key','']]},
];
function request<T>(action:string,settings?:unknown):Promise<T>{return studioRequest<T>(action,{settings});}
export function ApiSettings({onSaved}:{onSaved:(caps:Capabilities)=>void}){
 const [snapshot,setSnapshot]=useState<SettingsView|null>(null),[values,setValues]=useState<Record<string,string>>({}),[clear,setClear]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;void request<SettingsView>('settings').then(data=>{if(active){setSnapshot(data);setValues(data.values);}}).catch(e=>{if(active)setError((e as Error).message);});return()=>{active=false;};},[]);
 async function save(){if(!snapshot)return;setBusy(true);setError('');setMessage('');try{const data=await request<{settings:SettingsView;capabilities:Capabilities}>('save_settings',{revision:snapshot.revision,values,clearSecrets:clear});setSnapshot(data.settings);setValues(data.settings.values);setClear([]);onSaved(data.capabilities);setMessage('已保存并立即生效。新建作品时可选择“真实 API”；已有演示作品保持演示模式。配置尚未进行真实调用验证。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel api-settings"><div className="section-head"><h2><KeyRound size={18}/>API 配置</h2><span>本机保存 · 无需重启</span></div><p className="help">密钥保存在本机服务端配置文件中，不回显，也不写入浏览器存储。密钥留空会保留现有值；勾选“清除”才会删除。</p>{!snapshot&&!error&&<output>正在读取配置…</output>}{error&&<p className="banner error" role="alert">{error}</p>}{snapshot&&<form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} style={{border:0,padding:0}}>{groups.map(group=><section className="api-group" key={group.title}><h3>{group.title}</h3><p className="help">{group.description}</p><div className="form-grid">{group.fields.map(([key,label,placeholder])=>{const isSecret=key.endsWith('_KEY');return <div key={key}><label>{label}{isSecret&&<small> · {snapshot.secrets[key]?'已设置':'未设置'}</small>}{key==='IMAGE_PROVIDER'||key==='OPENAI_IMAGE_MODEL'?<select value={values[key]||(key==='IMAGE_PROVIDER'?'gateway':'gpt-image-2')} onChange={e=>{setValues({...values,[key]:e.target.value});setMessage('');}}>{(key==='IMAGE_PROVIDER'?[['gateway','统一媒体网关（原配置）'],['openai','OpenAI 文生图（直接接入）'],['fal','fal.ai（FLUX / Seedream）']]:[['gpt-image-2','GPT Image 2'],['gpt-image-1.5','GPT Image 1.5'],['gpt-image-1','GPT Image 1'],['gpt-image-1-mini','GPT Image 1 Mini']]).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<input type={isSecret?'password':'text'} autoComplete="off" spellCheck={false} value={values[key]??''} placeholder={isSecret?(snapshot.secrets[key]?'留空保留现有密钥':'输入密钥'):placeholder} disabled={clear.includes(key)} onChange={e=>{setValues({...values,[key]:e.target.value});setMessage('');}}/>}</label>{isSecret&&snapshot.secrets[key]&&<label className="clear-key"><input type="checkbox" checked={clear.includes(key)} onChange={e=>{setClear(e.target.checked?[...clear,key]:clear.filter(k=>k!==key));setValues({...values,[key]:''});setMessage('');}}/>清除此服务的密钥</label>}</div>;})}</div></section>)}<Button type="submit" disabled={busy}><Save/>{busy?'正在保存…':'保存 API 设置'}</Button></fieldset></form>}{message&&<output className="banner">{message}</output>}</section>;
}
