'use client';
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { AssetUpload } from './asset-upload';
import { AssetSetPanel } from './asset-set-panel';
import { AssetPromptCard } from './asset-prompt-card';
import { Button } from './ui/button';
import type { Project } from '@/lib/studio/types';
export function AssetLibrary({project,busy,act}:{project:Project;busy:boolean;act:(action:string,data?:Record<string,unknown>)=>Promise<unknown>}){
 const [showHistory,setShowHistory]=useState(false),[designDrafts,setDesignDrafts]=useState<Record<string,string>>({});
 const [setFilter,setSetFilter]=useState('all');
 const [notes,setNotes]=useState<Record<string,string>>({}),[refs,setRefs]=useState<string[]>([]);
 const refreshAction=useRef(act);useEffect(()=>{refreshAction.current=act;},[act]);
 useEffect(()=>{void refreshAction.current('get');},[project.id]);
 const assets=project.production?.library??[],running=assets.find(a=>a.status==='running');
 useEffect(()=>{if(!running||busy)return;const timer=setTimeout(()=>void act('asset_poll',{assetId:running.id}),3000);return()=>clearTimeout(timer);},[running,busy,act]);
 return <section className="panel"><h2>参考资产库 · 当前设计</h2><Button variant="outline" disabled={busy} onClick={()=>void act('get')}>重新读取最新候选</Button><p className="help">主图用 FLUX.2 Turbo；单图修改用 FLUX Edit；多图合成用 Seedream 4.5。真实模式需要单独配置 fal.ai 密钥。先确认人物和场景主图，再进入分镜。图片链接由 fal 托管，可能过期，请及时保存重要素材。</p>
 {!assets.length&&<Button disabled={busy} onClick={()=>void act('asset_inventory')}>从已保存设定建立人物、场景、道具清单</Button>}
 <div className="queue-actions"><Button variant="outline" disabled={busy||!!running} onClick={()=>void act('asset_refresh_inventory')}>重新分析资产设计（保留旧图，不生图）</Button><label><input type="checkbox" checked={showHistory} onChange={e=>setShowHistory(e.target.checked)}/>显示旧设定归档</label></div><p className="help">每个视角与细节都是独立图片候选：先确认纯资产主图，再建立视角清单并逐张生成。确认细节图不会替换主图。</p><label>查看设定图套组<select value={setFilter} onChange={e=>setSetFilter(e.target.value)}><option value="all">全部资产</option>{assets.filter(a=>!a.retired&&!a.parentId&&!a.viewId).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><div className="form-grid">{assets.filter(a=>!a.retired&&(setFilter==='all'||(a.parentId??a.id)===setFilter)).map(a=><article key={a.id} className="panel"><h3>{a.name} · V{a.version}</h3><small>{a.viewId?'视角 / 细节':a.kind==='character'?'人物主图':a.kind==='background'?'场景主图':a.kind==='prop'?'独立道具':'修改候选'}</small>{a.promptVersion!=='3.0.0'&&<p className="help">旧版提示词：请重新分析资产设计，避免继续使用混合设定。</p>}<p>{a.retired?'旧设定归档':a.approved?'已确认':a.status==='running'?'正在生成':a.status==='ready'?'待人工确认':a.status==='failed'?'生成失败':'待生成'}</p>
 {a.origin==='upload'&&<p>来源：本地上传 · {a.uploadedFilename}</p>}{a.status==='draft'&&!a.retired&&<AssetUpload assetId={a.id} disabled={busy||!!running} onUpload={act}/>}
 {a.url&&<><Image src={a.url} alt={a.name} width={360} height={240} unoptimized style={{width:'100%',height:'auto'}}/><a href={a.url} target="_blank" rel="noreferrer">打开原图</a></>}
 {a.error&&<output>{a.error}</output>}<AssetPromptCard asset={a} library={assets}/>{a.status==='draft'&&a.design&&!a.viewId&&a.kind!=='variant'&&<div><label>调整此资产的可见设计<textarea value={designDrafts[a.id]??a.design.description} onChange={e=>setDesignDrafts({...designDrafts,[a.id]:e.target.value})}/></label><Button variant="outline" disabled={busy||!designDrafts[a.id]?.trim()||designDrafts[a.id]===a.design.description} onClick={()=>void act('asset_edit_design',{assetId:a.id,notes:designDrafts[a.id]})}>保存设计并重新编译提示词（不生图）</Button></div>}
 {a.status==='running'&&<Button disabled={busy} onClick={()=>void act('asset_abandon',{assetId:a.id})}>停止本地跟踪</Button>}{a.status==='failed'&&<Button disabled={busy} onClick={()=>void act('asset_retry',{assetId:a.id})}>{a.remoteId?'恢复任务跟踪':'创建重试候选（可能再次计费）'}</Button>}<div className="queue-actions"><Button disabled={busy||a.retired||!!running||a.status!=='draft'||(designDrafts[a.id]!==undefined&&designDrafts[a.id]!==a.design?.description)||(project.mode==='live'&&a.promptVersion!=='3.0.0')} onClick={()=>void act('asset_generate',{assetId:a.id})}>生成此候选</Button>{!a.retired&&['ready','failed'].includes(a.status)&&<Button variant="outline" disabled={busy||!!running||(project.mode==='live'&&a.promptVersion!=='3.0.0')} onClick={()=>void act('asset_regenerate',{assetId:a.id})}>不满意，重新生成{project.mode==='live'?'（付费）':''}</Button>}<Button disabled={busy||a.retired||a.status!=='ready'||a.approved||(project.mode==='live'&&a.promptVersion!=='3.0.0')} onClick={()=>void act('asset_approve',{assetId:a.id})}>确认使用</Button></div>
 {!a.retired&&a.kind!=='variant'&&<Button variant="outline" disabled={busy||!!running} onClick={()=>void act('asset_rebuild',{assetId:a.id})}>创建多面板设定板候选（不生图）</Button>}{a.approved&&a.design&&!a.viewId&&<AssetSetPanel source={a} library={assets} busy={busy||!!running} act={act}/>}{a.approved&&<><label><input type="checkbox" checked={refs.includes(a.id)} onChange={e=>setRefs(e.target.checked?[...refs,a.id]:refs.filter(id=>id!==a.id))}/>作为补充参考图</label><textarea aria-label={a.name+'修改要求'} placeholder="仅描述这张图的一个修改，例如：保持人物身份，把外套改成黑色。设定板可在同一图内包含多视角与细节。" value={notes[a.id]??''} onChange={e=>setNotes({...notes,[a.id]:e.target.value})}/><Button disabled={busy||!notes[a.id]?.trim()} onClick={()=>void act('asset_variant',{assetId:a.id,notes:notes[a.id],referenceIds:refs.filter(id=>id!==a.id)})}>创建修改候选（保留原版）</Button></>}
 </article>)}</div>{showHistory&&<section className="panel"><h3>历史归档 · 不会发送给生图模型</h3><p>以下是旧生成记录，保留原始提示词用于追溯，不能继续生成或确认使用。</p>{assets.filter(a=>a.retired).map(a=><details key={a.id}><summary>{a.name} · 旧版本</summary>{a.url&&<a href={a.url} target="_blank" rel="noreferrer">查看旧图</a>}<p style={{whiteSpace:'pre-wrap'}}>{a.prompt}</p></details>)}</section>}</section>;
}
