'use client';
import { useState } from 'react';
import type { BriefDecision } from '@/lib/studio/brief-decisions';
import { Button } from '@/components/ui/button';
import type { Project } from '@/lib/studio/types';
export function ClarificationPanel({project,answers,onAnswers,busy,onAction}:{project:Project;answers:Record<string,string>;onAnswers:(v:Record<string,string>)=>void;busy:boolean;onAction:(action:string,data:Record<string,unknown>,navigate?:boolean)=>Promise<unknown>}){
 const [notes,setNotes]=useState('');const brief=project.brief;
 const [draftDecisions,setDraftDecisions]=useState<{brief:Project['brief'];values:BriefDecision[]}|null>(null);
 const decisions=draftDecisions&&draftDecisions.brief===brief?draftDecisions.values:brief?.decisions??[];
 const decisionDirty=JSON.stringify(decisions)!==JSON.stringify(brief?.decisions??[]);
 const unresolved=brief?.assumptions.some(a=>!decisions.some(d=>d.suggestion===a&&(d.choice!=='revise'||!!d.replacement?.trim())));
 function choose(suggestion:string,choice:BriefDecision['choice'],replacement?:string){setDraftDecisions({brief,values:[...decisions.filter(d=>d.suggestion!==suggestion),{suggestion,choice,...(choice==='revise'?{replacement:replacement??''}:{})}]});}
const editing=project.production?.node==='clarify';
 async function submit(action:string){if(decisionDirty)return;const result=await onAction(action,{answers,notes},true);if(result)setNotes('');}
 if(!brief)return <div><p className="help">本幕尚未进行针对性创意分析。</p>{editing&&<Button disabled={busy} onClick={()=>void submit('analyze_brief')}>阅读创意，分析需要澄清的内容</Button>}</div>;
 return <div className="clarification"><div className="section-head"><h2>创意开发编辑的理解</h2><small>第 {brief.round} 轮 · {brief.source==='model'?'模型分析':'演示关键词分析'}</small></div><p className="brief-summary">{brief.summary}</p>{brief.known.length>0&&<details><summary>已确认的信息与依据 · {brief.known.length} 项</summary>{brief.known.map((f,i)=><div className="known-fact" key={i}><strong>{f.topic}</strong><p>{f.value}</p><small>依据：“{f.evidence}”</small></div>)}</details>}{brief.assumptions.length>0&&<div className="brief-assumptions"><h3>待你确认的建议</h3><p className="help">逐条选择后保存。未选择不代表同意；不接受的建议不会作为编剧要求。</p>{brief.assumptions.map((a,i)=>{const d=decisions.find(d=>d.suggestion===a);return <div className="known-fact" key={i}><p>{a}</p>{editing?<><label>你的决定<select disabled={busy} value={d?.choice??''} onChange={e=>choose(a,e.target.value as BriefDecision['choice'])}><option value="" disabled>请选择</option><option value="accept">接受</option><option value="reject">不接受，保持原始要求</option><option value="revise">修改后采用</option></select></label>{d?.choice==='revise'&&<label>修改后的要求<textarea disabled={busy} maxLength={2000} value={d.replacement??''} onChange={e=>choose(a,'revise',e.target.value)}/></label>}</>:<p>{d?.choice==='accept'?'已接受':d?.choice==='reject'?'不接受':d?.choice==='revise'?'修改后采用：'+d.replacement:'未逐条确认（旧记录）'}</p>}</div>;})}{editing&&<Button disabled={busy||!decisionDirty||decisions.some(d=>d.choice==='revise'&&!d.replacement?.trim())} onClick={()=>void onAction('brief_decisions',{decisions,answers})}>保存建议选择（不调用模型）</Button>}</div>}{brief.history.length>0&&<details><summary>已回答的澄清问题</summary>{brief.history.map((h,i)=><div className="known-fact" key={i}><strong>{h.question}</strong><p>{h.answer}</p></div>)}</details>}
 {editing&&<>{brief.ready?<p className="pass">关键问题已回答。请逐条处理建议并保存，再开始编剧。</p>:<div className="fields"><h3>这些选择会影响成片</h3>{project.questions.map((q,i)=><div key={q.id} className="clarify-question"><label><span className="question-number">0{i+1}</span>{q.label}<textarea disabled={busy} placeholder={q.placeholder} value={answers[q.id]??''} onChange={e=>onAnswers({...answers,[q.id]:e.target.value})}/></label>{q.why&&<p className="help">为什么问：{q.why}</p>}<div className="answer-options">{q.options?.map(option=><Button key={option} variant="outline" disabled={busy} onClick={()=>onAnswers({...answers,[q.id]:option})}>{option}</Button>)}</div></div>)}</div>}<label>补充要求 / 纠正理解（可选）<textarea disabled={busy} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="例如：信不是来自未来，而是写给未来的自己；不要旁白。"/></label>
 {!brief.ready&&<Button disabled={busy||decisionDirty||project.questions.some(q=>!answers[q.id]?.trim())} onClick={()=>void submit(brief.round>=3?'confirm_brief':'clarify_answers')}>{brief.round>=3?'确认当前回答，允许编剧补充细节':'提交回答，检查是否仍有歧义'}</Button>}
 {brief.ready&&notes.trim()&&<Button disabled={busy||decisionDirty} onClick={()=>void submit(brief.round>=3?'confirm_brief':'clarify_answers')}>更新补充要求并检查理解</Button>}
 {brief.ready&&!notes.trim()&&<Button disabled={busy||decisionDirty||unresolved} onClick={()=>void submit('plan')}>按已保存的选择生成结构化剧本</Button>}
 </>}</div>;
}
