'use client';
import { ShotIntentView } from './shot-intent-view';
import { MotionEditor } from './motion-editor';
import type { Shot, Camera } from '@/lib/studio/types';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { cameraPosition } from '@/lib/studio/animatic';
export const movementLabels={fixed:'固定',push:'推进',pull:'拉远',track:'横移',orbit:'环绕'};
export const sizeLabels={wide:'全景',medium:'中景',close:'特写'};
export function ShotEditor({shot,onChange,onSave,onMotionPlan,busy,dirty}:{shot:Shot;onChange:(s:Shot)=>void;onSave:()=>void;onMotionPlan?:(notes:string)=>void;busy:boolean;dirty:boolean}){
 const set=(patch:Partial<Shot>)=>onChange({...shot,...patch});const camera=(patch:Partial<Camera>)=>set({camera:{...shot.camera,...patch}});
 const performance=(index:number,patch:Partial<NonNullable<Shot['performance']>[number]>)=>set({performance:shot.performance?.map((line,i)=>i===index?{...line,...patch}:line)});
 const map=(p:{x:number;z:number})=>({x:210+p.x*18,y:205-p.z*12});const start=map(cameraPosition(shot,0)),end=map(cameraPosition(shot,1));
 const path=Array.from({length:31},(_,i)=>{const p=map(cameraPosition(shot,i/30));return (i?'L ':'M ')+p.x+' '+p.y;}).join(' ');
 const slider=(label:string,v:number,min:number,max:number,step:number,change:(v:number)=>void)=><label className="range-label">{label}<span>{v}</span><Slider aria-label={label} min={min} max={max} step={step} value={[v]} onValueChange={v=>change(Array.isArray(v)?v[0]:v)}/></label>;
 return <div className="shot-editor"><div className="section-head"><h2>镜头参数</h2><span>{shot.id.toUpperCase()}</span></div><label>镜头标题<input value={shot.title} onChange={e=>set({title:e.target.value})}/></label><label>画面与动作<textarea value={shot.description} onChange={e=>set({description:e.target.value})}/></label><div className="form-grid"><label>场景编号<input value={shot.scene} onChange={e=>set({scene:e.target.value})}/></label><label>景别<select value={shot.size} onChange={e=>set({size:e.target.value as Shot['size']})}>{Object.entries(sizeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>运镜<select value={shot.camera.movement} onChange={e=>{const movement=e.target.value as Camera['movement'];camera({movement,...(movement==='fixed'?{end:{...shot.camera.start}}:{})});}}>{Object.entries(movementLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>转场<select value={shot.transition} onChange={e=>set({transition:e.target.value as Shot['transition']})}><option value="cut">直接切换</option><option value="dissolve">叠化建议</option></select></label></div>
 <div className="camera-map"><svg viewBox="0 0 420 240" aria-label="俯视运镜路径，横轴为左右位置，纵轴为主体距离"><defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M 30 0 L 0 0 0 30" fill="none" stroke="#344047" strokeWidth=".5"/></pattern></defs><rect width="420" height="240" fill="url(#grid)"/><line x1="210" y1="0" x2="210" y2="210" stroke="#6b7478" strokeDasharray="5 5"/><circle cx="210" cy="215" r="7" fill="#acb6bd"/><text x="225" y="222" fill="#a3b1b9" fontSize="13">局部坐标原点</text><path d={path} stroke="#d5f584" strokeWidth="2" fill="none"/><circle cx={start.x} cy={start.y} r="7" fill="#d5f584"/><circle cx={end.x} cy={end.y} r="7" fill="#151a1c" stroke="#d5f584" strokeWidth="2"/><text x={start.x+12} y={start.y-10} fill="#d5f584" fontSize="13">起点</text><text x={end.x+12} y={end.y+19} fill="#d5f584" fontSize="13">终点</text></svg><small>俯视路径 · 米 · 通过下方滑块调整</small></div>
 <div className="form-grid">{<label>镜头时长（秒；超过模型上限按长镜头续接）<input type="number" min={2} max={3600} step={0.5} value={shot.duration} onChange={e=>set({duration:Number(e.target.value)})}/></label>}{slider('焦距（mm）',shot.camera.lens,18,135,1,v=>camera({lens:v}))}</div>
 {(['start','end'] as const).map(key=><div key={key} className="path-controls"><h3>{key==='start'?'起点':'终点'}</h3><div className="form-grid">{(['x','y','z'] as const).map(axis=><div key={axis}>{slider(({x:'左右 X',y:'高度 Y',z:'距离 Z'})[axis],shot.camera[key][axis],axis==='x'?-10:.1,axis==='z'?15:10,.1,v=>camera({[key]:{...shot.camera[key],[axis]:v}}))}</div>)}</div></div>)}
 <label>速度曲线<select value={shot.camera.easing} onChange={e=>camera({easing:e.target.value as Camera['easing']})}><option value="ease-in-out">平滑起停</option><option value="linear">匀速</option></select></label>
 <details><summary>场记与声音</summary><label>对白<textarea value={shot.dialogue} onChange={e=>set({dialogue:e.target.value})}/></label><label>声音设计<input value={shot.sound} onChange={e=>set({sound:e.target.value})}/></label>{(['startState','endState'] as const).map(key=><div key={key}><h3>{key==='startState'?'起始状态':'结束状态'}</h3>{(['pose','wardrobe','props','light'] as const).map(field=><label key={field}>{{pose:'动作',wardrobe:'服装',props:'道具',light:'光线'}[field]}<input value={shot[key][field]} onChange={e=>set({[key]:{...shot[key],[field]:e.target.value}})}/></label>)}<div className="form-grid"><label>轴线侧<select value={shot[key].axis} onChange={e=>set({[key]:{...shot[key],axis:e.target.value}})}><option>A</option><option>B</option></select></label><label>画面运动方向<select value={shot[key].screenDirection} onChange={e=>set({[key]:{...shot[key],screenDirection:e.target.value}})}><option value="left-to-right">左 → 右</option><option value="right-to-left">右 → 左</option><option value="static">静止</option></select></label></div></div>)}</details>
 <details open={shot.duration>15?true:undefined}><summary>编辑动作节拍与对白时间窗</summary><p>时间从本镜 0 秒起算。修改镜头时长后请核对动作与对白时间窗；长镜头会避开正在说话的时间段进行接续，不会自动拉长台词。</p>{shot.intent?<label>动作节拍（按秒列出起势、执行、反应与停顿）<textarea value={shot.intent.actionTiming} onChange={e=>set({intent:{...shot.intent!,actionTiming:e.target.value}})}/></label>:<p>本镜尚无动作设计依据，请让分镜导演根据已确认剧本补齐，再调整动作节拍。</p>}{shot.performance?.map((line,index)=><div className="asset-prompt-card" key={(line.sourceSceneId??shot.scene)+':'+line.dialogueIndex+':'+index}><p><strong>{line.characterId}</strong> · “{line.text}”</p><div className="form-grid"><label>开始秒<input type="number" min={0} max={shot.duration} step={0.1} value={line.start} onChange={e=>performance(index,{start:Number(e.target.value)})}/></label><label>结束秒<input type="number" min={0} max={shot.duration} step={0.1} value={line.end} onChange={e=>performance(index,{end:Number(e.target.value)})}/></label></div><label>语气与表演意图<textarea value={line.delivery} onChange={e=>performance(index,{delivery:e.target.value})}/></label><label>语速与变化<input value={line.pace} onChange={e=>performance(index,{pace:e.target.value})}/></label></div>)}{!shot.performance?.length&&shot.dialogue.trim()&&<p>已有对白但缺少表演时间窗。请让分镜导演根据已确认对白补齐说话人、原文及时间窗；这里只编辑已有依据，不自动猜测台词归属。</p>}</details>
 <ShotIntentView shot={shot}/><MotionEditor shot={shot} onChange={onChange} onPlan={dirty?undefined:onMotionPlan} busy={busy}/><Button className="full" disabled={busy||!dirty} onClick={onSave}>{dirty?'保存修改 · 下游素材将失效':'已保存'}</Button></div>;
}


