import type { CreativeBrief } from './clarification.ts';
import type { Screenplay } from './screenplay.ts';
export type Question = { id: string; label: string; placeholder: string; why?:string; options?:string[]; required?:boolean };
export type CameraPoint = { x: number; y: number; z: number };
export type Camera = { movement: 'fixed' | 'push' | 'pull' | 'track' | 'orbit'; lens: number; start: CameraPoint; end: CameraPoint; easing: 'linear' | 'ease-in-out' };
export type ContinuityState = { pose: string; screenDirection: 'left-to-right' | 'right-to-left' | 'static'; wardrobe: string; props: string; light: string; axis: 'A' | 'B' };
export type Shot = { motion?:import('./motion.ts').MotionProgram; id: string; scene: string; title: string; beat: string; description: string; dialogue: string; sound: string; duration: number; size: 'wide' | 'medium' | 'close'; transition: 'cut' | 'dissolve'; camera: Camera; startState: ContinuityState; endState: ContinuityState; referenceOrigin?:'upload'|'generated'; referenceFilename?:string; referenceUrl?: string; videoUrl?: string; referenceMode?: 'demo' | 'live'; videoMode?: 'demo' | 'live' };
export type Bible = { character: string; appearance: string; location: string; lighting: string; palette: string; props: string; style: string; negative: string };
export type Plan = { title: string; logline: string; synopsis: string; bible: Bible; shots: Shot[] };
export type Job = { id: string; shotId: string; kind: 'image' | 'video'; status: 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled'; mode: 'demo' | 'live'; revision: number; createdAt: number; startedAt?: number; finishedAt?: number; error?: string; remoteId?: string; outputUrl?: string; input?: unknown; retries?:number; qaRetries?:number };
export type Project = {durationMode?:'auto'|'manual';durationReason?:string; id: string; revision: number; idea: string; title: string; createdAt: number; updatedAt: number; duration: number; ratio: '16:9' | '9:16' | '1:1'; mode: 'demo' | 'live'; phase: 'clarify' | 'planned'; questions: Question[]; answers: Record<string,string>; plan?: Plan; jobs: Job[]; production?: Production; brief?:CreativeBrief };
export type Issue = { shotId: string; level: 'error' | 'warning'; code: string; message: string };
export type Capabilities = { llm: boolean; image: boolean; video: boolean; llmModel: string; imageModel: string; videoModel: string };
export type NodeId = 'clarify' | 'script' | 'assets' | 'storyboard' | 'continuity' | 'prompts' | 'generation' | 'qa' | 'assembly' | 'complete';
export type Production = {autoRun?:import('./autopilot.ts').AutoRun;agentConfig?:import('./team-config.ts').AgentConfig;agentConfigRevision?:number;teamReports?:import('./team.ts').TeamReport[];costumeSelections?:Record<string,string>; node: NodeId; script?: Screenplay; scriptHistory?: {at:number;script:Screenplay}[]; library?:Asset[]; assets?: { bible:Bible; seed:number; locked:boolean }; scriptApproved:boolean; skillVersions?:Record<string,string>; continuityReview?:{revision:number;summary:string;findings:{shotId:string;evidence:string;message:string;suggestion:string}[]}; editPlan?:{summary:string;notes:{shotId:string;edit:string;audio:string}[];limitations:string[]}; renderApprovedRevision?:number; prompts?: {shotId:string; prompt:string}[]; qa: { shotId:string; verdict:'passed'|'needs_review'|'rejected'; source:'demo'|'human'|'vision'; notes:string; attempt:number }[]; maxRetries:number; events:{at:number;node:NodeId;role:string;message:string}[] };


export type Asset = {origin?:'upload'|'generated';uploadedFilename?:string;costumeOf?:string;setName?:string;setReview?:{at:number;notes:string;viewIds:string[]};evidence?:string;design?:import('./asset-design.ts').AssetDesign;promptVersion?:string;viewId?:string;sourceAssetId?:string;retired?:boolean;id:string;name:string;kind:'character'|'background'|'prop'|'variant';prompt:string;referenceIds:string[];parentId?:string;version:number;approved:boolean;status:'draft'|'running'|'ready'|'failed';url?:string;remoteId?:string;error?:string;model?:string;createdAt:number};
